Review of Milestone 2.
abouhid/Social_media_app pull request #2
Opened 2020-10-13 22:19 UTC by KelynPNjeri

This PR herein contains the following:
1. A way for a user to add friends.
2. Unit tests for all models.
3. Integration tests for the user view.

2020-10-14 00:08 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi team! Well done implementing the required relationships amongst your models. There are some requirements that you still need to implement to complete this milestone though. These include:
- [ ] A user should be able to see friendship requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] A user has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] A user should be able to reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] The button to invite a user to friendship should appear on both the users' list page and on a single user's page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Posts timeline should include posts written by the logged-in user and his/her friends. Your current version displays all posts to any logged-in user. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Well done writing the tests for your associations. Consider adding some validation tests and integration tests. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] __[Note]__ It appears that you set up your linting correctly but it is still unable to run the checks on your pull request. Consider replacing your config files with new ones and see if this persists.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-10-16 17:57 UTC, abouhid commented
All of the issues were fixed and we even took it further and finished the following two milestones! Thank you for the help.

2020-10-16 18:34 UTC, kubilaycaglayan requested changes
Hello Team 👋
Status: Changes Required ♻️

Great job! You fulfilled the requirements that the previous TSE mentioned. 👍👏😊
There's just one thing I noticed when looking at show.html.erb in users view.
We should keep the logic away from the views. 
Please work on it, I am sharing the necessary documentation with you.


### - [ ] [REQUIRED] There shoud be absolutely NO logic in views.

>Views are only for displaying information that became available to it from its corresponding controller not generating it.

**Resources** 
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

### That's it, team! After making the changes you can request another code review 😇

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

2020-10-16 18:34 UTC, kubilaycaglayan commented on app/views/users/show.html.erb
> + <% unless current_user.friendship_requested?(@user) || current_user.friend?(@user) %>
:bulb: There should be no logic in the views.

2020-10-16 20:59 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

2020-10-16 23:12 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-10-16 23:47 UTC, merged